language: node_js
node_js:
- 0.1
notifications:
  slack:
    secure: MUOOm6qJXDZ5trIVxFFt2yTmfKeYD0fVbO6OLLM8uiwEhs64Bb7qsaiNYYvMVxIy/QHz/87/fD98ij19dAm8tN56GFkycg6ch5sdyyOBB5CoISV3XgHgb9tShQIM4hUYKmu5k3jYxY+nL6VAsfcYlpfPNcXScNN6b4WH3E38GOs=
before_install:
- openssl aes-256-cbc -K $encrypted_4fb3bbb94e82_key -iv $encrypted_4fb3bbb94e82_iv
  -in .travis/config.json.enc -out config.json -d
- openssl aes-256-cbc -K $encrypted_bf01f8a98783_key -iv $encrypted_bf01f8a98783_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- chmod 600 .travis/deploy_key
- eval `ssh-agent -s`
- ssh-add .travis/deploy_key
